### ISSUE TITLE
where is the state.gd?

### ISSUE THREAD

**Issue by JustusPan** [godot-addons/godot-finite-state-machine#2]
Hello,
At the beginning of each sample XX_state.gd, extends "state.gd" will report a error cause there is no such a file, is that a missing file? How can I make the example work?

**Comment by brandonlamb** [comment]
See:

https://github.com/godot-addons/godot-finite-state-machine/blob/master/addons/godot-finite-state-machine/state_machine.gd#L169

It's a class defined in the state_machine.gd file

**Comment by JustusPan** [comment]
Now I can make it work well. 
Thank you very much!
