### ISSUE TITLE
AssetLib Version is Outdated

### ISSUE THREAD

**Issue by sundayz** [godot-addons/godot-finite-state-machine#6]
Nice plugin, but the AssetLib version seems to be missing the fixes from commit f5a2e66 onwards.

**Comment by brandonlamb** [comment]
Finally coming back to code on this after like... 2 years :|

**Comment by brandonlamb** [comment]
Submitted an update to asset store for v1.1.0

**Comment by aaronfranke** [comment]
@brandonlamb Is there a reason the asset library points to https://github.com/brandonlamb/godot-finite-state-machine instead of https://github.com/godot-addons/godot-finite-state-machine ?

**Comment by brandonlamb** [comment]
Crap!

**Comment by brandonlamb** [comment]
Good catch haha, submitted an update
