### ISSUE TITLE
Pure LSP implementation

### ISSUE THREAD

**Issue by ploover** [godot-addons/godot-finite-state-machine#8]
For those of us that want to use other code editors, is there any way to get a pure LSP server to run? So we could use something like emacs or vim?

**Comment by NathanLovato** [comment]
Currently, emacs and vim won't support LSP. Oliver Frank recently ported the LSP in Godot so it can work with most text editors, but that happened after the 3.2 release. 

Then, there's nothing in particular to do from within a godot project to provide LSP support: as long as you have Godot 3.2+ running, and a client that can connect to its server (currently via websocket, with the VSCode or Atom plugins), you'll get ~the same autocompletion you get in the editor.

**Comment by ploover** [comment]
I just realized that I opened the issue on the wrong repo. Facepalm. Still a great answer, put me on the right track for further reading, thanksĄ

**Comment by NathanLovato** [comment]
Note @ploover that we're working on a new GDScript mode for emacs ( https://github.com/GDQuest/emacs-gdscript-mode ), Oliver wrote a gdscript client for emacs-lsp, and now it's just a matter of time.
